services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_DB: YOUR_DB
      POSTGRES_USER: YOUR_USER
      POSTGRES_PASSWORD: YOUR_PASS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
